# Generated by Django 3.0.6 on 2020-05-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('accessories', 'accessories'), ('footwear', 'footwear'), ('pants', 'pants'), ('shirts', 'shirts'), ('tshirts', 'tshirts'), ('shorts', 'shorts')], max_length=12)),
                ('size', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
